package model;

public class InjectionModel extends MyModel{
	public InjectionModel(byte data[]) {
		int point = 6;
		SERVICE_PRESSURE = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));    
		SERVICE_TEMP = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));    
		INV_RPM = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		SERVICE_PRESSURE1 = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));     
		SERVICE_TEMP1 = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));    
		ALARM = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));     
		FAULT_FLG = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));     
		FAULT_INV = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));     
		OUTPUT_STATUS = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));     
		INPUT_STATUS = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));   
		COUNT_STATUS = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));   
		CP_STATUS = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));     
		RUN_MODE = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));   
		EXT_RUN_STOP = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));   
		P_MAX_PRESS = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		EMER_STOP_PRESSURE = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF)); // 16
		INV_TARGET_PRESSURE = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		INV_INDIRECT_PRESSURE = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		INV_DIRECT_PRESSURE = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		UNLOAD_PRESSURE = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		LOAD_PRESSURE = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		AUTO_STOP_TIME = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		AUTO_STOP_DELAY_TIME = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		STOP_DELAY_TIME = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		VENT_TIME = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		YD_CONVERSION_TIME = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		RUN_SELECT_MODE = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		REMOTE_TYPE = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF)); 
		MANUAL_UNLOAD_MODE = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		FAN_ONOFF_MODE = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		LOAD_TEMP = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));    
		FAN_ON_TEMP = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));    
		FAN_OFF_TEMP = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		TEMP_ALARM_TEMP = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));    
		TEMP_FAULT_TEMP = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));    
		ADMIN_PASSWORD = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));      
		GREES_USETIME = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		INV_FREQ = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));      
		INV_MAX_RPM = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		INV_MIN_RPM = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		AIRFILTER_USETIME = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		OILFILTER_USETIME = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		SEPARATOR_USETIME = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		OIL_USETIME = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		TOTAL_AIR_FILT_TIME = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));  
		TOTAL_OIL_FILT_TIME = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));  
		TOTAL_SEPARATOR_TIME = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		TOTAL_OIL_TIME = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));     
		TOTAL_LOAD_TIME = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		TOTAL_UNLOAD_TIME = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));   
		TOTAL_AUTOSTOP_TIME = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));    
		TOTAL_STOP_TIME = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));    
		TOTAL_RUN_TIME_L = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));    
		TOTAL_RUN_TIME_H = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		TOTAL_RUN_COUNT_L = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		TOTAL_RUN_COUNT_H = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));     
		SYSTEM_ID = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		MODEL_1 = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));      
		MODEL_2 = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));      
		VERSION = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));      
		TOTAL_GREES_TIME = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		VERSION_NUM = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));      
		SERIAL_YEAR = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));      
		SERIAL_LOT = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));     
		SERIAL_NUMBER = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
	}
	public short SERVICE_PRESSURE;
	public short SERVICE_TEMP;    
	public short INV_RPM;
	public short SERVICE_PRESSURE1;     
	public short SERVICE_TEMP1;    
	public short ALARM;     
	public short FAULT_FLG;     
	public short FAULT_INV;     
	public short OUTPUT_STATUS;     
	public short INPUT_STATUS;   
	public short COUNT_STATUS;   
	public short CP_STATUS;     
	public short RUN_MODE;   
	public short EXT_RUN_STOP;   
	public short P_MAX_PRESS;
	public short EMER_STOP_PRESSURE;
	public short INV_TARGET_PRESSURE;
	public short INV_INDIRECT_PRESSURE;
	public short INV_DIRECT_PRESSURE;
	public short UNLOAD_PRESSURE;
	public short LOAD_PRESSURE;
	public short AUTO_STOP_TIME;
	public short AUTO_STOP_DELAY_TIME;
	public short STOP_DELAY_TIME;
	public short VENT_TIME;
	public short YD_CONVERSION_TIME;
	public short RUN_SELECT_MODE;
	public short REMOTE_TYPE; 
	public short MANUAL_UNLOAD_MODE;
	public short FAN_ONOFF_MODE;
	public short LOAD_TEMP;    
	public short FAN_ON_TEMP;    
	public short FAN_OFF_TEMP;
	public short TEMP_ALARM_TEMP;    
	public short TEMP_FAULT_TEMP;    
	public short ADMIN_PASSWORD;      
	public short GREES_USETIME;
	public short INV_FREQ;      
	public short INV_MAX_RPM;
	public short INV_MIN_RPM;
	public short AIRFILTER_USETIME;
	public short OILFILTER_USETIME;
	public short SEPARATOR_USETIME;
	public short OIL_USETIME;
	public short TOTAL_AIR_FILT_TIME;  
	public short TOTAL_OIL_FILT_TIME;  
	public short TOTAL_SEPARATOR_TIME;
	public short TOTAL_OIL_TIME;     
	public short TOTAL_LOAD_TIME;
	public short TOTAL_UNLOAD_TIME;   
	public short TOTAL_AUTOSTOP_TIME;    
	public short TOTAL_STOP_TIME;    
	public short TOTAL_RUN_TIME_L;    
	public short TOTAL_RUN_TIME_H;
	public short TOTAL_RUN_COUNT_L;
	public short TOTAL_RUN_COUNT_H;     
	public short SYSTEM_ID;
	public short MODEL_1;      
	public short MODEL_2;      
	public short VERSION;      
	public short TOTAL_GREES_TIME;
	public short VERSION_NUM;      
	public short SERIAL_YEAR;      
	public short SERIAL_LOT;     
	public short SERIAL_NUMBER;     
}
