package model;

public class OilModel extends MyModel{
	public OilModel(byte data[]) {
		int point = 6;
		P1 = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		P2 = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		P3 = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		P4 = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		P5 = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		P6 = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		T1 = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		T2 = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		T3 = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		T4 = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		T5 = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		T6 = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		T7 = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		T8 = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		T9 = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		T10 = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		T11 = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		T12 = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		T13 = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		T14 = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mALARM_FLAG = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mFAULT_FLG_L = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mFAULT_FLG_H = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mFAULT_INV = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mCP_STATUS = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mOUTPUT_STATUS = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mINPUT_STATUS = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mCOUNT_STATUS = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mINV_RPM = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mRUN_MODE = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mREAL_YEARWEEK = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mREAL_MONTHDAY = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mREAL_HOURMIN = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mREAL_SEC = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mEXT_RUN_STOP = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mINV_TargetP = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mINV_InDirectP = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mINV_DirectP = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mEMER_STOP_P = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mUNLOAD_P = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mLOAD_P = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mAUTO_STOP_MIN = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mOIL_START_SEC = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mYD_CONVERSION_SEC = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mSYSTEM_ID = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mDRIVE_SET_MODE = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mMANUAL_UNLOAD_MODE = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mREMOTE_TYPE = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mTOUT1_FAULT_TEMP = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mTOUT2_FAULT_TEMP = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mTOIL_FAULT_TEMP = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mPMAX_LIMIT = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mP2IN_FAULT = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mPOIL_FAULT = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mPAIRFILTER_DEF_ALARM = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mLOAD_DELAY_SEC = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mSTOP_DELAY_SEC = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mAIRFILTER_USE_LIMIT = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mOILFILTER_USE_LIMIT = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mOIL_USE_LIMIT = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mGRESS_USE_LIMIT = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mLOAD_TEMP = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mMODEL_1 = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mVERSION_1 = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mVERSION_2 = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mVERSION_NUM = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mINV_FREQ = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mINV_MAX_RPM = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mINV_MIN_RPM = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mTOTAL_AIR_FILT_TIME = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mTOTAL_OIL_FILT_TIME = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mTOTAL_OIL_TIME = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mTOTAL_GRESS_TIME = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mTOTAL_UNLOAD_TIME = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mTOTAL_LOAD_TIME = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mTOTAL_AUTOSTOP_TIME = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mTOTAL_STOP_TIME = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mTOTAL_RUN_TIME_L = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mTOTAL_RUN_TIME_H = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mTOTAL_RUN_COUNT_L = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mTOTAL_RUN_COUNT_H = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mSERIAL_YEAR = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
		mSERIAL_LOT = (short) (((data[point++] & 0xFF) << 8) | (data[point++] & 0xFF));
	}
	
	public short P1;
	public short P2;
	public short P3;
	public short P4;
	public short P5;
	public short P6;
	public short T1;
	public short T2;
	public short T3;
	public short T4;
	public short T5;
	public short T6;
	public short T7;
	public short T8;
	public short T9;
	public short T10;
	public short T11;
	public short T12;
	public short T13;
	public short T14;
	public short mALARM_FLAG;
	public short mFAULT_FLG_L;
	public short mFAULT_FLG_H;
	public short mFAULT_INV;
	public short mCP_STATUS;
	public short mOUTPUT_STATUS;
	public short mINPUT_STATUS;
	public short mCOUNT_STATUS;
	public short mINV_RPM;
	public short mRUN_MODE;
	public short mREAL_YEARWEEK;
	public short mREAL_MONTHDAY;
	public short mREAL_HOURMIN;
	public short mREAL_SEC;
	public short mEXT_RUN_STOP;
	public short mINV_TargetP;
	public short mINV_InDirectP;
	public short mINV_DirectP;
	public short mEMER_STOP_P;
	public short mUNLOAD_P;
	public short mLOAD_P;
	public short mAUTO_STOP_MIN;
	public short mOIL_START_SEC;
	public short mYD_CONVERSION_SEC;
	public short mSYSTEM_ID;
	public short mDRIVE_SET_MODE;
	public short mMANUAL_UNLOAD_MODE;
	public short mREMOTE_TYPE;
	public short mTOUT1_FAULT_TEMP;
	public short mTOUT2_FAULT_TEMP;
	public short mTOIL_FAULT_TEMP;
	public short mPMAX_LIMIT;
	public short mP2IN_FAULT;
	public short mPOIL_FAULT;
	public short mPAIRFILTER_DEF_ALARM;
	public short mLOAD_DELAY_SEC;
	public short mSTOP_DELAY_SEC;
	public short mAIRFILTER_USE_LIMIT;
	public short mOILFILTER_USE_LIMIT;
	public short mOIL_USE_LIMIT;
	public short mGRESS_USE_LIMIT;
	public short mLOAD_TEMP;
	public short mMODEL_1;
	public short mVERSION_1;
	public short mVERSION_2;
	public short mVERSION_NUM;
	public short mINV_FREQ;
	public short mINV_MAX_RPM;
	public short mINV_MIN_RPM;
	public short mTOTAL_AIR_FILT_TIME;
	public short mTOTAL_OIL_FILT_TIME;
	public short mTOTAL_OIL_TIME;
	public short mTOTAL_GRESS_TIME;
	public short mTOTAL_UNLOAD_TIME;
	public short mTOTAL_LOAD_TIME;
	public short mTOTAL_AUTOSTOP_TIME;
	public short mTOTAL_STOP_TIME;
	public short mTOTAL_RUN_TIME_L;
	public short mTOTAL_RUN_TIME_H;
	public short mTOTAL_RUN_COUNT_L;
	public short mTOTAL_RUN_COUNT_H;
	public short mSERIAL_YEAR;
	public short mSERIAL_LOT;
}
